version: '3.8'

services:
  image_generate_ui:
    build: .
    ports:
      - "8501:8501"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - BEDROCK_MODEL_ID=anthropic.claude-3-sonnet-20240229-v1:0
      - BEDROCK_EMBEDDING_MODEL_ID=amazon.titan-embed-text-v1
    restart: unless-stopped